using System.IO;

namespace CepHoras.Control;

internal static class InstallationIdentity
{
    // Generated by LocalSystem in the existing admin/SYSTEM-only directory.
    // The ID is random; it is never derived from a SID, machine name or hardware.
    internal static Guid ReadOrCreate()
    {
        PolicyStore.SecureDirectory();
        return ReadOrCreateAt(PolicyStore.Root);
    }

    internal static Guid ReadOrCreateAt(string directory)
    {
        var path = Path.Combine(directory, "installation-id");
        if (File.Exists(path))
        {
            var content = File.ReadAllText(path);
            if (Guid.TryParseExact(content, "D", out var existing) && existing != Guid.Empty)
                return existing;
            throw new InvalidDataException("Identidade local de instalação inválida.");
        }
        var created = Guid.NewGuid();
        var temporary = path + "." + Guid.NewGuid().ToString("N") + ".tmp";
        try
        {
            using (var stream = new FileStream(temporary, FileMode.CreateNew, FileAccess.Write, FileShare.None,
                4096, FileOptions.WriteThrough))
            using (var writer = new StreamWriter(stream))
            {
                writer.Write(created.ToString("D"));
                writer.Flush();
                stream.Flush(flushToDisk: true);
            }
            File.Move(temporary, path, overwrite: false);
        }
        finally { if (File.Exists(temporary)) File.Delete(temporary); }
        return created;
    }
}
