/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/organization/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    before?: string;
                    pageSize?: number;
                    /** @description Required for SystemAdmin: organization to administer. Other roles remain restricted to their own organization. */
                    organizationId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuditEventResponse"][];
                        "application/json": components["schemas"]["AuditEventResponse"][];
                        "text/json": components["schemas"]["AuditEventResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/web/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WebSessionResponse"];
                        "application/json": components["schemas"]["WebSessionResponse"];
                        "text/json": components["schemas"]["WebSessionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/web/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WebSessionResponse"];
                        "application/json": components["schemas"]["WebSessionResponse"];
                        "text/json": components["schemas"]["WebSessionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/web/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TokenResponse"];
                        "application/json": components["schemas"]["TokenResponse"];
                        "text/json": components["schemas"]["TokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                    "text/json": components["schemas"]["RefreshRequest"];
                    "application/*+json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TokenResponse"];
                        "application/json": components["schemas"]["TokenResponse"];
                        "text/json": components["schemas"]["TokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LogoutRequest"];
                    "text/json": components["schemas"]["LogoutRequest"];
                    "application/*+json": components["schemas"]["LogoutRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AcceptInvitationRequest"];
                    "text/json": components["schemas"]["AcceptInvitationRequest"];
                    "application/*+json": components["schemas"]["AcceptInvitationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TokenResponse"];
                        "application/json": components["schemas"]["TokenResponse"];
                        "text/json": components["schemas"]["TokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ForgotPasswordRequest"];
                    "text/json": components["schemas"]["ForgotPasswordRequest"];
                    "application/*+json": components["schemas"]["ForgotPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ResetPasswordRequest"];
                    "text/json": components["schemas"]["ResetPasswordRequest"];
                    "application/*+json": components["schemas"]["ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserResponse"];
                        "application/json": components["schemas"]["UserResponse"];
                        "text/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateProfileRequest"];
                    "text/json": components["schemas"]["UpdateProfileRequest"];
                    "application/*+json": components["schemas"]["UpdateProfileRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserResponse"];
                        "application/json": components["schemas"]["UserResponse"];
                        "text/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                    "text/json": components["schemas"]["ChangePasswordRequest"];
                    "application/*+json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SessionResponse"][];
                        "application/json": components["schemas"]["SessionResponse"][];
                        "text/json": components["schemas"]["SessionResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    search?: string;
                    status?: components["schemas"]["OrganizationStatus"];
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrganizationResponsePagedResponse"];
                        "application/json": components["schemas"]["OrganizationResponsePagedResponse"];
                        "text/json": components["schemas"]["OrganizationResponsePagedResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateOrganizationRequest"];
                    "text/json": components["schemas"]["CreateOrganizationRequest"];
                    "application/*+json": components["schemas"]["CreateOrganizationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrganizationResponse"];
                        "application/json": components["schemas"]["OrganizationResponse"];
                        "text/json": components["schemas"]["OrganizationResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizations/{organizationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrganizationResponse"];
                        "application/json": components["schemas"]["OrganizationResponse"];
                        "text/json": components["schemas"]["OrganizationResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizations/{organizationId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ChangeOrganizationStatusRequest"];
                    "text/json": components["schemas"]["ChangeOrganizationStatusRequest"];
                    "application/*+json": components["schemas"]["ChangeOrganizationStatusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/admin/organizations/{organizationId}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InvitationResponse"][];
                        "application/json": components["schemas"]["InvitationResponse"][];
                        "text/json": components["schemas"]["InvitationResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizations/{organizationId}/invitations/{invitationId}/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                    invitationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizations/{organizationId}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path: {
                    organizationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserResponsePagedResponse"];
                        "application/json": components["schemas"]["UserResponsePagedResponse"];
                        "text/json": components["schemas"]["UserResponsePagedResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    search?: string;
                    status?: components["schemas"]["UserStatus"];
                    role?: components["schemas"]["UserRole"];
                    product?: components["schemas"]["Product"];
                    page?: number;
                    pageSize?: number;
                    /** @description Required for SystemAdmin: organization to administer. Other roles remain restricted to their own organization. */
                    organizationId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserResponsePagedResponse"];
                        "application/json": components["schemas"]["UserResponsePagedResponse"];
                        "text/json": components["schemas"]["UserResponsePagedResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description Required for SystemAdmin: organization to administer. Other roles remain restricted to their own organization. */
                    organizationId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InvitationResponse"][];
                        "application/json": components["schemas"]["InvitationResponse"][];
                        "text/json": components["schemas"]["InvitationResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    /** @description Required for SystemAdmin: organization to administer. Other roles remain restricted to their own organization. */
                    organizationId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["InviteUserRequest"];
                    "text/json": components["schemas"]["InviteUserRequest"];
                    "application/*+json": components["schemas"]["InviteUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InvitationResponse"];
                        "application/json": components["schemas"]["InvitationResponse"];
                        "text/json": components["schemas"]["InvitationResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/invitations/{invitationId}/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    /** @description Required for SystemAdmin: organization to administer. Other roles remain restricted to their own organization. */
                    organizationId?: string;
                };
                header?: never;
                path: {
                    invitationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/invitations/{invitationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: {
                    /** @description Required for SystemAdmin: organization to administer. Other roles remain restricted to their own organization. */
                    organizationId?: string;
                };
                header?: never;
                path: {
                    invitationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: {
                    /** @description Required for SystemAdmin: organization to administer. Other roles remain restricted to their own organization. */
                    organizationId?: string;
                };
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateUserRequest"];
                    "text/json": components["schemas"]["UpdateUserRequest"];
                    "application/*+json": components["schemas"]["UpdateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserResponse"];
                        "application/json": components["schemas"]["UserResponse"];
                        "text/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/plugin/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    /** @description Required for SystemAdmin: organization to administer. Other roles remain restricted to their own organization. */
                    organizationId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreatePluginGrantRequest"];
                    "text/json": components["schemas"]["CreatePluginGrantRequest"];
                    "application/*+json": components["schemas"]["CreatePluginGrantRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PluginGrantResponse"];
                        "application/json": components["schemas"]["PluginGrantResponse"];
                        "text/json": components["schemas"]["PluginGrantResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    organizationId?: string;
                    before?: string;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuditEventResponse"][];
                        "application/json": components["schemas"]["AuditEventResponse"][];
                        "text/json": components["schemas"]["AuditEventResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/time-control/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    includeInactive?: boolean;
                    asOf?: string;
                    /** @description Required for SystemAdmin: organization to administer. Other roles remain restricted to their own organization. */
                    organizationId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkforceTeamResponse"][];
                        "application/json": components["schemas"]["WorkforceTeamResponse"][];
                        "text/json": components["schemas"]["WorkforceTeamResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    /** @description Required for SystemAdmin: organization to administer. Other roles remain restricted to their own organization. */
                    organizationId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateWorkforceTeamRequest"];
                    "text/json": components["schemas"]["CreateWorkforceTeamRequest"];
                    "application/*+json": components["schemas"]["CreateWorkforceTeamRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkforceTeamResponse"];
                        "application/json": components["schemas"]["WorkforceTeamResponse"];
                        "text/json": components["schemas"]["WorkforceTeamResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/time-control/teams/{teamId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    asOf?: string;
                    /** @description Required for SystemAdmin: organization to administer. Other roles remain restricted to their own organization. */
                    organizationId?: string;
                };
                header?: never;
                path: {
                    teamId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkforceTeamResponse"];
                        "application/json": components["schemas"]["WorkforceTeamResponse"];
                        "text/json": components["schemas"]["WorkforceTeamResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: {
                    /** @description Required for SystemAdmin: organization to administer. Other roles remain restricted to their own organization. */
                    organizationId?: string;
                };
                header?: never;
                path: {
                    teamId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateWorkforceTeamRequest"];
                    "text/json": components["schemas"]["UpdateWorkforceTeamRequest"];
                    "application/*+json": components["schemas"]["UpdateWorkforceTeamRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkforceTeamResponse"];
                        "application/json": components["schemas"]["WorkforceTeamResponse"];
                        "text/json": components["schemas"]["WorkforceTeamResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/organization/time-control/teams/{teamId}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    includeHistory?: boolean;
                    asOf?: string;
                    /** @description Required for SystemAdmin: organization to administer. Other roles remain restricted to their own organization. */
                    organizationId?: string;
                };
                header?: never;
                path: {
                    teamId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TeamAssignmentResponse"][];
                        "application/json": components["schemas"]["TeamAssignmentResponse"][];
                        "text/json": components["schemas"]["TeamAssignmentResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    /** @description Required for SystemAdmin: organization to administer. Other roles remain restricted to their own organization. */
                    organizationId?: string;
                };
                header?: never;
                path: {
                    teamId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateTeamAssignmentRequest"];
                    "text/json": components["schemas"]["CreateTeamAssignmentRequest"];
                    "application/*+json": components["schemas"]["CreateTeamAssignmentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TeamAssignmentResponse"];
                        "application/json": components["schemas"]["TeamAssignmentResponse"];
                        "text/json": components["schemas"]["TeamAssignmentResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/time-control/teams/{teamId}/assignments/{assignmentId}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: {
                    /** @description Required for SystemAdmin: organization to administer. Other roles remain restricted to their own organization. */
                    organizationId?: string;
                };
                header?: never;
                path: {
                    teamId: string;
                    assignmentId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EndTeamAssignmentRequest"];
                    "text/json": components["schemas"]["EndTeamAssignmentRequest"];
                    "application/*+json": components["schemas"]["EndTeamAssignmentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TeamAssignmentResponse"];
                        "application/json": components["schemas"]["TeamAssignmentResponse"];
                        "text/json": components["schemas"]["TeamAssignmentResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/organization/time-control/external-identities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    source?: components["schemas"]["ExternalWorkforceSource"];
                    activeOnly?: boolean;
                    mapped?: boolean;
                    search?: string;
                    page?: number;
                    pageSize?: number;
                    /** @description Required for SystemAdmin: organization to administer. Other roles remain restricted to their own organization. */
                    organizationId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ExternalWorkforceIdentityResponsePagedResponse"];
                        "application/json": components["schemas"]["ExternalWorkforceIdentityResponsePagedResponse"];
                        "text/json": components["schemas"]["ExternalWorkforceIdentityResponsePagedResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/time-control/synchronizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    full?: boolean;
                    /** @description Required for SystemAdmin: organization to administer. Other roles remain restricted to their own organization. */
                    organizationId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkforceSyncResponse"];
                        "application/json": components["schemas"]["WorkforceSyncResponse"];
                        "text/json": components["schemas"]["WorkforceSyncResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/time-control/synchronizations/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description Required for SystemAdmin: organization to administer. Other roles remain restricted to their own organization. */
                    organizationId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkforceSyncResponse"];
                        "application/json": components["schemas"]["WorkforceSyncResponse"];
                        "text/json": components["schemas"]["WorkforceSyncResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/time-control/synchronizations/{batchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description Required for SystemAdmin: organization to administer. Other roles remain restricted to their own organization. */
                    organizationId?: string;
                };
                header?: never;
                path: {
                    batchId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkforceSyncResponse"];
                        "application/json": components["schemas"]["WorkforceSyncResponse"];
                        "text/json": components["schemas"]["WorkforceSyncResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/time-control/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    workforcePersonId?: string;
                    source?: components["schemas"]["ExternalWorkforceSource"];
                    search?: string;
                    /** @description Required for SystemAdmin: organization to administer. Other roles remain restricted to their own organization. */
                    organizationId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkforceAdminHistoryResponse"];
                        "application/json": components["schemas"]["WorkforceAdminHistoryResponse"];
                        "text/json": components["schemas"]["WorkforceAdminHistoryResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/time-control/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    search?: string;
                    page?: number;
                    pageSize?: number;
                    /** @description Required for SystemAdmin: organization to administer. Other roles remain restricted to their own organization. */
                    organizationId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkforcePersonResponsePagedResponse"];
                        "application/json": components["schemas"]["WorkforcePersonResponsePagedResponse"];
                        "text/json": components["schemas"]["WorkforcePersonResponsePagedResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/time-control/people/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    /** @description Required for SystemAdmin: organization to administer. Other roles remain restricted to their own organization. */
                    organizationId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["InviteWorkforcePersonRequest"];
                    "text/json": components["schemas"]["InviteWorkforcePersonRequest"];
                    "application/*+json": components["schemas"]["InviteWorkforcePersonRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InviteWorkforcePersonResponse"];
                        "application/json": components["schemas"]["InviteWorkforcePersonResponse"];
                        "text/json": components["schemas"]["InviteWorkforcePersonResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptInvitationRequest: {
            email?: string | null;
            code?: string | null;
            displayName?: string | null;
            password?: string | null;
            client?: components["schemas"]["ClientInfo"];
        };
        AuditEventResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            organizationId?: string | null;
            /** Format: uuid */
            actorUserId?: string | null;
            /** Format: uuid */
            targetUserId?: string | null;
            action?: string | null;
            /** @enum {unknown} */
            details?: null;
            ipAddress?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        ChangeOrganizationStatusRequest: {
            status?: components["schemas"]["OrganizationStatus"];
        };
        ChangePasswordRequest: {
            currentPassword?: string | null;
            newPassword?: string | null;
        };
        ClientInfo: {
            type?: string | null;
            version?: string | null;
            installationId?: string | null;
        };
        CreateOrganizationRequest: {
            name?: string | null;
            slug?: string | null;
            initialAdminEmail?: string | null;
            products?: components["schemas"]["Product"][] | null;
        };
        CreatePluginGrantRequest: {
            product?: components["schemas"]["Product"];
            pluginVersion?: string | null;
            installationId?: string | null;
        };
        CreateTeamAssignmentRequest: {
            /** Format: uuid */
            userId?: string;
            role?: components["schemas"]["TeamAssignmentRole"];
            /** Format: date */
            effectiveFrom?: string;
            /** Format: date */
            effectiveTo?: string | null;
        };
        CreateWorkforceTeamRequest: {
            name?: string | null;
        };
        EndTeamAssignmentRequest: {
            /** Format: date */
            effectiveTo?: string;
        };
        ExternalWorkforceIdentityResponse: {
            /** Format: uuid */
            id?: string;
            source?: components["schemas"]["ExternalWorkforceSource"];
            externalId?: string | null;
            displayName?: string | null;
            email?: string | null;
            isActive?: boolean;
            /** Format: date-time */
            lastSeenAt?: string;
            /** Format: uuid */
            workforcePersonId?: string | null;
        };
        ExternalWorkforceIdentityResponsePagedResponse: {
            items?: components["schemas"]["ExternalWorkforceIdentityResponse"][] | null;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int64 */
            total?: number;
        };
        /** @enum {string} */
        ExternalWorkforceSource: "monday" | "vrMais";
        ForgotPasswordRequest: {
            email?: string | null;
        };
        InvitationResponse: {
            /** Format: uuid */
            id?: string;
            email?: string | null;
            role?: components["schemas"]["UserRole"];
            canUseRevit?: boolean;
            canUseZwcad?: boolean;
            /** Format: date-time */
            expiresAt?: string;
            /** Format: date-time */
            acceptedAt?: string | null;
            /** Format: date-time */
            revokedAt?: string | null;
        };
        InviteUserRequest: {
            email?: string | null;
            role?: components["schemas"]["UserRole"];
            products?: components["schemas"]["Product"][] | null;
        };
        InviteWorkforcePersonRequest: {
            email?: string | null;
            displayName?: string | null;
            /** Format: uuid */
            mondayIdentityId?: string;
            /** Format: uuid */
            vrMaisIdentityId?: string;
        };
        InviteWorkforcePersonResponse: {
            person?: components["schemas"]["WorkforcePersonResponse"];
            invitation?: components["schemas"]["InvitationResponse"];
        };
        LoginRequest: {
            email?: string | null;
            password?: string | null;
            client?: components["schemas"]["ClientInfo"];
        };
        LogoutRequest: {
            refreshToken?: string | null;
        };
        OrganizationResponse: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            slug?: string | null;
            status?: components["schemas"]["OrganizationStatus"];
            /** Format: date-time */
            createdAt?: string;
        };
        OrganizationResponsePagedResponse: {
            items?: components["schemas"]["OrganizationResponse"][] | null;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int64 */
            total?: number;
        };
        /** @enum {string} */
        OrganizationStatus: "active" | "suspended" | "archived";
        PluginGrantResponse: {
            grantToken?: string | null;
            /** Format: date-time */
            expiresAt?: string;
        };
        /** @enum {string} */
        Product: "revit" | "zwcad";
        RefreshRequest: {
            refreshToken?: string | null;
        };
        ResetPasswordRequest: {
            email?: string | null;
            code?: string | null;
            newPassword?: string | null;
        };
        SessionResponse: {
            /** Format: uuid */
            id?: string;
            clientType?: string | null;
            clientVersion?: string | null;
            installationId?: string | null;
            ipAddress?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** Format: date-time */
            lastUsedAt?: string | null;
        };
        TeamAssignmentResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            teamId?: string;
            /** Format: uuid */
            userId?: string;
            userDisplayName?: string | null;
            userEmail?: string | null;
            role?: components["schemas"]["TeamAssignmentRole"];
            /** Format: date */
            effectiveFrom?: string;
            /** Format: date */
            effectiveTo?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @enum {string} */
        TeamAssignmentRole: "member" | "manager";
        TokenResponse: {
            accessToken?: string | null;
            /** Format: date-time */
            accessTokenExpiresAt?: string;
            refreshToken?: string | null;
            /** Format: date-time */
            refreshTokenExpiresAt?: string;
            user?: components["schemas"]["UserResponse"];
        };
        UpdateProfileRequest: {
            displayName?: string | null;
        };
        UpdateUserRequest: {
            displayName?: string | null;
            role?: components["schemas"]["UserRole"];
            status?: components["schemas"]["UserStatus"];
            products?: components["schemas"]["Product"][] | null;
        };
        UpdateWorkforceTeamRequest: {
            name?: string | null;
            isActive?: boolean;
        };
        UserResponse: {
            /** Format: uuid */
            id?: string;
            displayName?: string | null;
            email?: string | null;
            /** Format: uuid */
            organizationId?: string | null;
            role?: components["schemas"]["UserRole"];
            status?: components["schemas"]["UserStatus"];
            products?: components["schemas"]["Product"][] | null;
        };
        UserResponsePagedResponse: {
            items?: components["schemas"]["UserResponse"][] | null;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int64 */
            total?: number;
        };
        /** @enum {string} */
        UserRole: "systemAdmin" | "organizationAdmin" | "user";
        /** @enum {string} */
        UserStatus: "active" | "suspended" | "archived";
        WebSessionResponse: {
            accessToken?: string | null;
            /** Format: date-time */
            accessTokenExpiresAt?: string;
            /** Format: date-time */
            sessionExpiresAt?: string;
            user?: components["schemas"]["UserResponse"];
        };
        WorkforceAdminHistoryResponse: {
            /** Format: date */
            from?: string;
            /** Format: date */
            to?: string;
            /** Format: date-time */
            generatedAt?: string;
            people?: components["schemas"]["WorkforcePersonHistoryResponse"][] | null;
        };
        WorkforcePersonHistoryResponse: {
            /** Format: uuid */
            workforcePersonId?: string;
            /** Format: uuid */
            userId?: string | null;
            displayName?: string | null;
            email?: string | null;
            records?: components["schemas"]["WorkforceTimeRecordResponse"][] | null;
        };
        WorkforcePersonResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string | null;
            displayName?: string | null;
            email?: string | null;
            monday?: components["schemas"]["ExternalWorkforceIdentityResponse"];
            vrMais?: components["schemas"]["ExternalWorkforceIdentityResponse"];
            /** Format: uuid */
            invitationId?: string | null;
            /** Format: date-time */
            invitationExpiresAt?: string | null;
            /** Format: date-time */
            invitationAcceptedAt?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        WorkforcePersonResponsePagedResponse: {
            items?: components["schemas"]["WorkforcePersonResponse"][] | null;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int64 */
            total?: number;
        };
        WorkforceSyncResponse: {
            /** Format: uuid */
            id?: string;
            status?: components["schemas"]["WorkforceSyncStatus"];
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            completedAt?: string | null;
            sources?: components["schemas"]["WorkforceSyncSourceResponse"][] | null;
        };
        WorkforceSyncSourceResponse: {
            source?: components["schemas"]["ExternalWorkforceSource"];
            status?: components["schemas"]["WorkforceSyncStatus"];
            /** Format: int32 */
            receivedCount?: number;
            /** Format: int32 */
            createdCount?: number;
            /** Format: int32 */
            updatedCount?: number;
            /** Format: int32 */
            deactivatedCount?: number;
            /** Format: int32 */
            timeRecordReceivedCount?: number;
            /** Format: int32 */
            timeRecordCreatedCount?: number;
            /** Format: int32 */
            timeRecordUpdatedCount?: number;
            /** Format: int32 */
            timeRecordRemovedCount?: number;
            completeSnapshot?: boolean;
            /** Format: date */
            coverageFrom?: string | null;
            /** Format: date */
            coverageTo?: string | null;
            errorCode?: string | null;
            errorMessage?: string | null;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            completedAt?: string | null;
        };
        /** @enum {string} */
        WorkforceSyncStatus: "running" | "succeeded" | "partiallySucceeded" | "failed";
        WorkforceTeamResponse: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            isActive?: boolean;
            /** Format: int32 */
            activeMembers?: number;
            /** Format: int32 */
            activeManagers?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        WorkforceTimeRecordResponse: {
            /** Format: uuid */
            id?: string;
            source?: components["schemas"]["ExternalWorkforceSource"];
            externalKey?: string | null;
            /** Format: date */
            workDate?: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            endedAt?: string | null;
            /** Format: int32 */
            durationSeconds?: number | null;
            state?: string | null;
            title?: string | null;
            url?: string | null;
            detailsJson?: string | null;
            /** Format: date-time */
            lastSyncedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
